import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";

import "./globals.css";
import NavBar from "./NavBar";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";
import QueryClientProvider from "./QueryClientProvider";
import { Theme } from "@radix-ui/themes";
import { ThemeProvider } from "next-themes";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Issue Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Theme appearance="inherit">
          <QueryClientProvider>
            <ThemeProvider attribute="class">
              <NavBar />
              <main className="p-5">{children}</main>
              <Toaster />
            </ThemeProvider>
          </QueryClientProvider>
        </Theme>
      </body>
    </html>
  );
}
